### ISSUE TITLE
TypeError: Cannot read property 'plnx' of unde fined

### ISSUE THREAD

**Issue by talvasconcelos** [passabilities/crypto-exchange#10]
Having this issue, maybe because API's are changing? 

`const crypto = require('crypto-exchange')

let pairFetch = ['BTC_USD', 'LTC_USD', 'ETH_BTC']

crypto.bitfinex.ticker(pairFetch)
  .then(console.log)`

"UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'bitfinex' of
undefined
"

At least Poloniex, Bittrex, Kraken, Bitfinex are throwing this error. Gdax is working fine.

**Comment by passabilities** [comment]
What version are you using? Try fetching the most recent version (v2.2.3)

**Comment by passabilities** [comment]
@talvasconcelos can you confirm that #11 fixes the problem for you? I have been unable to produce this error running the latest version.

**Comment by kroitor** [comment]
@passabilities I'm having the same issues with the latest version from npm (2.2.3)

```shell
mbp:crypto-exchange igorkroitor$ node --version
v8.0.0-nightly2017030539f7e72440
mbp:crypto-exchange igorkroitor$ npm ls crypto-exchange
/Users/igorkroitor/crypto-exchange
└── crypto-exchange@2.2.3 

mbp:crypto-exchange igorkroitor$ cat test.js 
```

```JavaScript
"use strict";
const cryptoexchange = require('crypto-exchange')
let pairFetch = ['BTC_USD', 'LTC_USD', 'ETH_BTC']
cryptoexchange.bitfinex.ticker(pairFetch).then(console.log)
cryptoexchange.kraken.ticker(pairFetch).then(console.log)
cryptoexchange.poloniex.ticker(pairFetch).then(console.log)
```

```shell
mbp:crypto-exchange igorkroitor$ node test.js 
(node:17293) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): TypeError: Cannot read property 'bitfinex' of undefined
(node:17293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17293) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): TypeError: Cannot read property 'kraken' of undefined
(node:17293) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'plnx' of undefined
mbp:crypto-exchange igorkroitor$ 
```

P.S. Don't know if that's a proper usage.

**Comment by passabilities** [comment]
Was able to reproduce the error after fresh install. Indeed #11 fixed the issue thanks!

**Comment by kroitor** [comment]
This issue is gone in 2.2.4, confirmed.

**Comment by talvasconcelos** [comment]
sorry haven't had time...
