### ISSUE TITLE
Bitfinex: Support multiple wallets for Balance

### ISSUE THREAD

**Issue by siedi** [passabilities/crypto-exchange#15]
Bitfinex has multiple wallets, i.e. for types = ['exchange', 'trading', 'funding']

Right now, only the exchange wallet is returned for the balance. In order to be compatible with all exchanges, I suggest adding the type (wallet) as a parameter for all exchanges. Of course, others might have just one wallet. 

Does that make sense?

**Comment by passabilities** [comment]
Yes, I noticed that as I was building this out. I don't use personally use Bitfinex and was confused by the different types of wallets. Could you help me understand what each wallet type purpose is?

I can add a type parameter for Bitfinex to allow this.

**Comment by passabilities** [comment]
I added a fix for this. For Bitfinex, you can pass a `type` in the options. See the README for fetching balances and addresses.

**Comment by siedi** [comment]
Thanks for fixing (also another bug included in the balance function). Unfortunately, there is a new issue introduced by the refactoring of the balance method. The caching you introduced creates a class variable `balances`, which conflicts with the method name `balances`, thus, when calling node complaints:
`TypeError: bitfinex.balances is not a function`
Also, the in [Line109](https://github.com/passabilities/crypto-exchange/blob/2c5e09269d5203e81f9ea5e55730362c4d073e1f/src/exchanges/bitfinex.js#L109) the alt variable is not set before when it gets assigned.

And would you mind merging it to the history branch?

Thanks again!

**Comment by siedi** [comment]
Just to explain the different wallet types:

- exchange is for "regular" buying or selling of assets/coins (like physically so you can transfer it from/to another wallet), similar to what you do e.g. on GDAX
- trading is used for real trading, like when you open long or short positions. The wallet is needed to fund these trades and "collect" you wins (or losses) when closing the open positions.
- funding, hm, never used it.

Hope my explanation makes sense.

**Comment by passabilities** [comment]
Ok those bugs should be fixed now. Thanks for the heads up. What would you liked merged with the history branch? I'm not quite done with it; i have plenty more to add for other exchanges.

**Comment by passabilities** [comment]
I just rebased `history` on top of `master` so it should have all those changes, if thats what you meant.

**Comment by siedi** [comment]
Works. Thanks!

**Comment by siedi** [comment]
Works. Thanks!
