### ISSUE TITLE
Binance support

### ISSUE THREAD

**Issue by gauraviitr** [passabilities/crypto-exchange#19]
Can you add support for binance ? 

Thanks !!

**Comment by passabilities** [comment]
This is something that I will definitely add to my list! I only have limited time but will keep you updated.

**Comment by Alifar** [comment]
Great script... any update on Binance? As this is the biggest exchange nowadays.

Thanks for the great work!

**Comment by IAmStoxe** [comment]
I have created a pull request (https://github.com/passabilities/crypto-exchange/pull/23) to satisfy the initial implementation of Binance. Hope you guys like it 👍
