### ISSUE TITLE
tutorial for dummies

### ISSUE THREAD

**Issue by jpita** [passabilities/crypto-exchange#20]
Hi,

I'm trying to use this to check my balance on bitfinex.
I have no idea how to start, is it possible for you (or anyone that knows how) to write a step by step tutorial?

Thanks!

**Comment by passabilities** [comment]
Hey @jpita, thanks! It should be pretty self explanatory but have a look at the example in the [README here](https://github.com/passabilities/crypto-exchange#authenticated-methods). You will need an API key and secret from the Bittrex settings page. Once you do all that, you can just do this:

```
bittrex.balances().then( bals => {
})
```
