### ISSUE TITLE
Crypto-exchange vs. ccxt

### ISSUE THREAD

**Issue by Bomper** [passabilities/crypto-exchange#21]
Is this library still maintained? In the fast world of crypto, frequent updates are good. [CCXT](https://github.com/ccxt/ccxt) is updated almost live and the user base is 20x larger. How do the two libraries compare right now?

**Comment by passabilities** [comment]
Yes, I am still working on this project. It is hard to keep up everyday especially as I am the only one currently working on this. I am working to add support for transaction and deposit/withdrawal history. After I plan on adding more exchanges. 

CCXT is a great package as it supports a multitude of exchanges. I find it somewhat too large to comb through their documentation.

If anyone is willing to help out with this project, I would deeply appreciate it

**Comment by IAmStoxe** [comment]
I created a pull request to add Binance. Check it out #23

**Comment by SimonEast** [comment]
I guess this repo is pretty out-of-date now. Perhaps CCXT is the best option to use, currently.

**Comment by passabilities** [comment]
Unfortunately, yea. I haven't had any time to work on this project. It started off as a personal side project that I was unable to keep up with. Thank you for taking an interest tho!
